import lastmod from './lastmod.json';

// lib/seo/lastmod.json is generated by `npm run lastmod` (per-path dates from
// git history) and committed — Vercel builds on a shallow clone, so the dates
// must be computed locally, never at build time.
const LASTMOD: Record<string, string> = lastmod;

export function lastmodFor(path: string): string | undefined {
  return LASTMOD[path];
}
