import type { ToolMeta, ToolCategory } from './types';

const IMG_MIMES = ['image/png', 'image/jpeg', 'image/webp'];

export const TOOLS: readonly ToolMeta[] = [
  {
    id: 'merge',
    category: 'pdf',
    href: '/pdf/merge',
    i18nKey: 'tools.pdf.merge',
    keywords: ['merge', 'combine', 'join', 'pdf', 'fusion', 'fusionner'],
    acceptedMime: ['application/pdf'],
    status: 'stable',
  },
  {
    id: 'split',
    category: 'pdf',
    href: '/pdf/split',
    i18nKey: 'tools.pdf.split',
    keywords: ['split', 'extract', 'pages', 'pdf', 'decouper', 'découper'],
    acceptedMime: ['application/pdf'],
    status: 'stable',
  },
  {
    id: 'rotate',
    category: 'pdf',
    href: '/pdf/rotate',
    i18nKey: 'tools.pdf.rotate',
    keywords: ['rotate', 'orientation', 'pdf', 'pivoter'],
    acceptedMime: ['application/pdf'],
    status: 'stable',
  },
  {
    id: 'watermark',
    category: 'pdf',
    href: '/pdf/watermark',
    i18nKey: 'tools.pdf.watermark',
    keywords: ['watermark', 'stamp', 'logo', 'overlay', 'pdf', 'filigrane', 'tampon', 'cachet'],
    acceptedMime: ['application/pdf'],
    status: 'stable',
  },
  {
    id: 'resize',
    category: 'pdf',
    href: '/pdf/resize',
    i18nKey: 'tools.pdf.resize',
    keywords: [
      'resize', 'page size', 'a4', 'letter', 'a3', 'a5', 'legal',
      'scale', 'dimensions', 'redimensionner', 'taille page',
    ],
    acceptedMime: ['application/pdf'],
    status: 'stable',
  },
  {
    id: 'to-images',
    category: 'pdf',
    href: '/pdf/to-images',
    i18nKey: 'tools.pdf.to-images',
    keywords: ['pdf', 'png', 'jpg', 'image', 'render', 'export'],
    acceptedMime: ['application/pdf'],
    status: 'stable',
  },
  {
    id: 'extract-images',
    category: 'pdf',
    href: '/pdf/extract-images',
    i18nKey: 'tools.pdf.extract-images',
    keywords: [
      'extract', 'images', 'embedded', 'pictures', 'figures', 'pdf',
      'extraire', 'photos', 'récupérer',
    ],
    acceptedMime: ['application/pdf'],
    status: 'stable',
  },
  {
    id: 'from-images',
    category: 'pdf',
    href: '/pdf/from-images',
    i18nKey: 'tools.pdf.from-images',
    keywords: ['image', 'png', 'jpg', 'pdf', 'combine'],
    acceptedMime: IMG_MIMES,
    status: 'stable',
  },
  {
    id: 'convert',
    category: 'video',
    href: '/video/convert',
    i18nKey: 'tools.video.convert',
    keywords: ['video', 'convert', 'mp4', 'webm', 'gif', 'convertir'],
    acceptedMime: ['video/mp4', 'video/webm', 'video/quicktime', 'video/x-matroska'],
    status: 'stable',
  },
  {
    id: 'trim',
    category: 'video',
    href: '/video/trim',
    i18nKey: 'tools.video.trim',
    keywords: ['video', 'trim', 'cut', 'clip', 'decouper', 'découper'],
    acceptedMime: ['video/mp4', 'video/webm', 'video/quicktime', 'video/x-matroska'],
    status: 'stable',
  },
  {
    id: 'split',
    category: 'video',
    href: '/video/split',
    i18nKey: 'tools.video.split',
    keywords: [
      'video', 'split', 'divide', 'cut', 'segments', 'parts', 'chapters',
      'diviser', 'decouper', 'découper', 'segmenter', 'parties',
    ],
    acceptedMime: ['video/mp4', 'video/webm', 'video/quicktime', 'video/x-matroska'],
    status: 'stable',
  },
  {
    id: 'merge',
    category: 'video',
    href: '/video/merge',
    i18nKey: 'tools.video.merge',
    keywords: ['video', 'merge', 'concat', 'concatenate', 'join', 'combine', 'fusionner', 'concatener', 'concaténer'],
    acceptedMime: ['video/mp4', 'video/webm', 'video/quicktime', 'video/x-matroska'],
    status: 'stable',
  },
  {
    id: 'compress',
    category: 'video',
    href: '/video/compress',
    i18nKey: 'tools.video.compress',
    keywords: ['video', 'compress', 'reduce', 'size', 'compresser', 'reduire', 'réduire'],
    acceptedMime: ['video/mp4', 'video/webm', 'video/quicktime', 'video/x-matroska'],
    status: 'stable',
  },
  {
    id: 'resize',
    category: 'video',
    href: '/video/resize',
    i18nKey: 'tools.video.resize',
    keywords: ['video', 'resize', 'scale', 'dimensions', '720p', '1080p', 'redimensionner'],
    acceptedMime: ['video/mp4', 'video/webm', 'video/quicktime', 'video/x-matroska'],
    status: 'stable',
  },
  {
    id: 'mute',
    category: 'video',
    href: '/video/mute',
    i18nKey: 'tools.video.mute',
    keywords: ['video', 'mute', 'remove audio', 'silence', 'no sound', 'couper son', 'sans son', 'muet'],
    acceptedMime: ['video/mp4', 'video/webm', 'video/quicktime', 'video/x-matroska'],
    status: 'stable',
  },
  {
    id: 'crop',
    category: 'video',
    href: '/video/crop',
    i18nKey: 'tools.video.crop',
    keywords: ['video', 'crop', 'cut', 'recadrer', 'rogner'],
    acceptedMime: ['video/mp4', 'video/webm', 'video/quicktime', 'video/x-matroska'],
    status: 'stable',
  },
  {
    id: 'rotate',
    category: 'video',
    href: '/video/rotate',
    i18nKey: 'tools.video.rotate',
    keywords: ['video', 'rotate', 'flip', 'mirror', '90', '180', 'pivoter', 'retourner', 'miroir'],
    acceptedMime: ['video/mp4', 'video/webm', 'video/quicktime', 'video/x-matroska'],
    status: 'stable',
  },
  {
    id: 'frames',
    category: 'video',
    href: '/video/frames',
    i18nKey: 'tools.video.frames',
    keywords: ['video', 'frames', 'extract', 'screenshots', 'thumbnail', 'images', 'extraire', 'captures'],
    acceptedMime: ['video/mp4', 'video/webm', 'video/quicktime', 'video/x-matroska'],
    status: 'stable',
  },
  {
    id: 'watermark',
    category: 'video',
    href: '/video/watermark',
    i18nKey: 'tools.video.watermark',
    keywords: ['video', 'watermark', 'overlay', 'logo', 'text', 'filigrane', 'tampon'],
    acceptedMime: ['video/mp4', 'video/webm', 'video/quicktime', 'video/x-matroska'],
    status: 'stable',
  },
  {
    id: 'short-studio',
    category: 'video',
    href: '/video/short-studio',
    i18nKey: 'tools.video.short-studio',
    keywords: [
      'short', 'shorts', 'studio', 'reel', 'reels', 'tiktok', 'youtube',
      'watermark', 'numbered', 'series', 'episode', 'split watermark',
      'court', 'numerotation', 'numérotation', 'série', 'serie', 'filigrane', 'épisode',
      'verticale', 'vertical', '9:16',
    ],
    acceptedMime: ['video/mp4', 'video/webm', 'video/quicktime', 'video/x-matroska'],
    status: 'stable',
  },
  {
    id: 'speed',
    category: 'video',
    href: '/video/speed',
    i18nKey: 'tools.video.speed',
    keywords: ['video', 'speed', 'slow motion', 'fast forward', 'playback rate', 'vitesse', 'ralenti', 'accéléré'],
    acceptedMime: ['video/mp4', 'video/webm', 'video/quicktime', 'video/x-matroska'],
    status: 'stable',
  },
  {
    id: 'tags',
    category: 'audio',
    href: '/audio/tags',
    i18nKey: 'tools.audio.tags',
    keywords: [
      'mp3', 'tags', 'id3', 'metadata', 'cover', 'album', 'artist', 'title', 'pochette',
      'métadonnées', 'modifier', 'éditer', 'edit',
    ],
    acceptedMime: [
      'audio/mpeg', 'audio/wav', 'audio/x-wav', 'audio/flac', 'audio/x-flac',
      'audio/mp4', 'audio/x-m4a', 'audio/aac', 'audio/ogg', 'audio/opus',
    ],
    status: 'stable',
  },
  {
    id: 'convert',
    category: 'audio',
    href: '/audio/convert',
    i18nKey: 'tools.audio.convert',
    keywords: [
      'audio', 'convert', 'mp3', 'wav', 'flac', 'aac', 'opus', 'm4a', 'ogg',
      'convertir', 'conversion', 'format', 'bitrate',
    ],
    acceptedMime: [
      'audio/mpeg', 'audio/wav', 'audio/x-wav', 'audio/flac', 'audio/x-flac',
      'audio/mp4', 'audio/x-m4a', 'audio/aac', 'audio/ogg', 'audio/opus',
    ],
    status: 'stable',
  },
  {
    id: 'extract',
    category: 'audio',
    href: '/audio/extract',
    i18nKey: 'tools.audio.extract',
    keywords: [
      'extract', 'audio', 'video', 'mp4 to mp3', 'mov to mp3', 'extraire',
      'son', 'piste audio', 'demuxer',
    ],
    acceptedMime: ['video/mp4', 'video/webm', 'video/quicktime', 'video/x-matroska'],
    status: 'stable',
  },
  {
    id: 'trim',
    category: 'audio',
    href: '/audio/trim',
    i18nKey: 'tools.audio.trim',
    keywords: [
      'trim', 'cut', 'clip', 'audio', 'mp3', 'découper', 'couper', 'raccourcir',
      'extraire passage',
    ],
    acceptedMime: [
      'audio/mpeg', 'audio/wav', 'audio/x-wav', 'audio/flac', 'audio/x-flac',
      'audio/mp4', 'audio/x-m4a', 'audio/aac', 'audio/ogg', 'audio/opus',
      'video/mp4', 'video/quicktime', 'video/webm', 'video/x-matroska',
    ],
    status: 'stable',
  },
  {
    id: 'merge',
    category: 'audio',
    href: '/audio/merge',
    i18nKey: 'tools.audio.merge',
    keywords: [
      'merge', 'combine', 'join', 'concatenate', 'audio', 'mp3',
      'fusionner', 'concatener', 'concaténer', 'joindre',
    ],
    acceptedMime: [
      'audio/mpeg', 'audio/wav', 'audio/x-wav', 'audio/flac', 'audio/x-flac',
      'audio/mp4', 'audio/x-m4a', 'audio/aac', 'audio/ogg', 'audio/opus',
    ],
    status: 'stable',
  },
  {
    id: 'volume',
    category: 'audio',
    href: '/audio/volume',
    i18nKey: 'tools.audio.volume',
    keywords: [
      'volume', 'gain', 'normalize', 'loudness', 'loudnorm', 'fade', 'fade in', 'fade out',
      'audio', 'mp3', 'normaliser', 'fondu', 'amplifier',
    ],
    acceptedMime: [
      'audio/mpeg', 'audio/wav', 'audio/x-wav', 'audio/flac', 'audio/x-flac',
      'audio/mp4', 'audio/x-m4a', 'audio/aac', 'audio/ogg', 'audio/opus',
    ],
    status: 'stable',
  },
  {
    id: 'convert',
    category: 'image',
    href: '/image/convert',
    i18nKey: 'tools.image.convert',
    keywords: ['image', 'convert', 'png', 'jpg', 'jpeg', 'webp', 'convertir', 'format'],
    acceptedMime: IMG_MIMES,
    status: 'stable',
  },
  {
    id: 'compress',
    category: 'image',
    href: '/image/compress',
    i18nKey: 'tools.image.compress',
    keywords: ['image', 'compress', 'reduce', 'size', 'compresser', 'reduire', 'réduire', 'optimize'],
    acceptedMime: IMG_MIMES,
    status: 'stable',
  },
  {
    id: 'resize',
    category: 'image',
    href: '/image/resize',
    i18nKey: 'tools.image.resize',
    keywords: ['image', 'resize', 'scale', 'redimensionner', 'taille', 'dimensions'],
    acceptedMime: IMG_MIMES,
    status: 'stable',
  },
  {
    id: 'crop',
    category: 'image',
    href: '/image/crop',
    i18nKey: 'tools.image.crop',
    keywords: ['image', 'crop', 'cut', 'rogner', 'recadrer', 'decouper', 'découper'],
    acceptedMime: IMG_MIMES,
    status: 'stable',
  },
  {
    id: 'rotate-flip',
    category: 'image',
    href: '/image/rotate-flip',
    i18nKey: 'tools.image.rotate-flip',
    keywords: ['image', 'rotate', 'flip', 'mirror', 'pivoter', 'miroir', 'retourner'],
    acceptedMime: IMG_MIMES,
    status: 'stable',
  },
  {
    id: 'remove-bg',
    category: 'image',
    href: '/image/remove-bg',
    i18nKey: 'tools.image.remove-bg',
    keywords: ['image', 'remove', 'background', 'bg', 'detourer', 'détourer', 'transparent', 'ai', 'ia'],
    acceptedMime: IMG_MIMES,
    status: 'beta',
  },
  {
    id: 'from-clipboard',
    category: 'image',
    href: '/image/from-clipboard',
    i18nKey: 'tools.image.from-clipboard',
    keywords: [
      'clipboard', 'paste', 'screenshot', 'capture',
      'presse-papier', 'coller', 'capture d\'ecran', 'capture-ecran',
      'cmd+v', 'ctrl+v',
    ],
    acceptedMime: [],
    status: 'stable',
  },
  {
    id: 'to-data-url',
    category: 'svg',
    href: '/svg/to-data-url',
    i18nKey: 'tools.svg.to-data-url',
    keywords: [
      'svg', 'data url', 'data uri', 'base64', 'url encode', 'css background',
      'data-url', 'data-uri', 'encoder',
    ],
    acceptedMime: ['image/svg+xml'],
    status: 'stable',
  },
  {
    id: 'viewer',
    category: 'svg',
    href: '/svg/viewer',
    i18nKey: 'tools.svg.viewer',
    keywords: [
      'svg', 'viewer', 'preview', 'inspect', 'view svg', 'open svg',
      'visionneuse', 'aperçu', 'inspecter',
    ],
    acceptedMime: ['image/svg+xml'],
    status: 'stable',
  },
  {
    id: 'to-png',
    category: 'svg',
    href: '/svg/to-png',
    i18nKey: 'tools.svg.to-png',
    keywords: [
      'svg', 'png', 'jpg', 'jpeg', 'webp', 'rasterize', 'convert', 'export',
      'rasteriser', 'rastériser', 'convertir', 'exporter',
    ],
    acceptedMime: ['image/svg+xml'],
    status: 'stable',
  },
  {
    id: 'editor',
    category: 'svg',
    href: '/svg/editor',
    i18nKey: 'tools.svg.editor',
    keywords: [
      'svg', 'editor', 'edit', 'colors', 'recolor', 'viewbox', 'transform',
      'editeur', 'éditer', 'modifier', 'recolorer',
    ],
    acceptedMime: ['image/svg+xml'],
    status: 'stable',
  },
  {
    id: 'favicon',
    category: 'svg',
    href: '/svg/favicon',
    i18nKey: 'tools.svg.favicon',
    keywords: [
      'favicon', 'ico', 'apple touch icon', 'manifest', 'pwa', 'svg favicon',
      'favicon generator', 'générateur favicon',
    ],
    acceptedMime: ['image/svg+xml'],
    status: 'stable',
  },
  {
    id: 'optimize',
    category: 'svg',
    href: '/svg/optimize',
    i18nKey: 'tools.svg.optimize',
    keywords: [
      'svg', 'optimize', 'minify', 'svgo', 'compress svg', 'shrink',
      'optimiser', 'minifier', 'compresser',
    ],
    acceptedMime: ['image/svg+xml'],
    status: 'stable',
  },
  {
    id: 'generate',
    category: 'password',
    href: '/password/generate',
    i18nKey: 'tools.password.generate',
    keywords: [
      'password', 'generate', 'random', 'secure',
      'mot de passe', 'générer', 'aleatoire', 'aléatoire',
    ],
    acceptedMime: [],
    status: 'stable',
  },
  {
    id: 'passphrase',
    category: 'password',
    href: '/password/passphrase',
    i18nKey: 'tools.password.passphrase',
    keywords: [
      'passphrase', 'diceware', 'words', 'memorable',
      'phrase', 'mots', 'memorisable', 'mémorisable',
    ],
    acceptedMime: [],
    status: 'stable',
  },
  {
    id: 'hash',
    category: 'password',
    href: '/password/hash',
    i18nKey: 'tools.password.hash',
    keywords: ['hash', 'sha', 'sha256', 'sha512', 'digest', 'checksum', 'empreinte'],
    acceptedMime: [],
    status: 'stable',
  },
  {
    id: 'bcrypt',
    category: 'password',
    href: '/password/bcrypt',
    i18nKey: 'tools.password.bcrypt',
    keywords: ['bcrypt', 'password', 'salt', 'hash', 'verify', 'sel', 'verifier', 'vérifier'],
    acceptedMime: [],
    status: 'stable',
  },
  {
    id: 'strength',
    category: 'password',
    href: '/password/strength',
    i18nKey: 'tools.password.strength',
    keywords: [
      'strength', 'entropy', 'check', 'meter',
      'force', 'entropie', 'evaluer', 'évaluer',
    ],
    acceptedMime: [],
    status: 'stable',
  },
  {
    id: 'format',
    category: 'json',
    href: '/json/format',
    i18nKey: 'tools.json.format',
    keywords: [
      'json', 'format', 'formatter', 'beautify', 'pretty print', 'minify',
      'sort keys', 'validate', 'embellir', 'compresser', 'valider',
    ],
    acceptedMime: ['application/json'],
    status: 'stable',
  },
  {
    id: 'tree',
    category: 'json',
    href: '/json/tree',
    i18nKey: 'tools.json.tree',
    keywords: [
      'json', 'tree', 'viewer', 'visualizer', 'explorer', 'browser', 'inspect',
      'arborescence', 'visionneuse', 'explorer', 'inspecter',
    ],
    acceptedMime: ['application/json'],
    status: 'stable',
  },
  {
    id: 'query',
    category: 'json',
    href: '/json/query',
    i18nKey: 'tools.json.query',
    keywords: [
      'json', 'query', 'jsonpath', 'filter', 'search', 'extract', 'find',
      'interroger', 'filtrer', 'extraire',
    ],
    acceptedMime: ['application/json'],
    status: 'stable',
  },
  {
    id: 'table',
    category: 'json',
    href: '/json/table',
    i18nKey: 'tools.json.table',
    keywords: [
      'json', 'table', 'array', 'rows', 'columns', 'sort', 'filter', 'search',
      'tableau', 'lignes', 'colonnes', 'trier', 'filtrer',
    ],
    acceptedMime: ['application/json'],
    status: 'stable',
  },
  {
    id: 'csv',
    category: 'json',
    href: '/json/csv',
    i18nKey: 'tools.json.csv',
    keywords: [
      'json', 'csv', 'convert', 'export', 'import', 'spreadsheet', 'tsv',
      'convertir', 'exporter', 'importer', 'tableur',
    ],
    acceptedMime: ['application/json', 'text/csv'],
    status: 'stable',
  },
  {
    id: 'diff',
    category: 'json',
    href: '/json/diff',
    i18nKey: 'tools.json.diff',
    keywords: [
      'json', 'diff', 'compare', 'comparison', 'changes',
      'comparer', 'différence', 'difference',
    ],
    acceptedMime: ['application/json'],
    status: 'stable',
  },
  {
    id: 'schema',
    category: 'json',
    href: '/json/schema',
    i18nKey: 'tools.json.schema',
    keywords: [
      'json', 'schema', 'validate', 'generate', 'ajv', 'json-schema', 'draft-07', 'draft-2020-12',
      'valider', 'générer', 'schéma',
    ],
    acceptedMime: ['application/json'],
    status: 'stable',
  },
  {
    id: 'case',
    category: 'text',
    href: '/text/case',
    i18nKey: 'tools.text.case',
    keywords: [
      'case', 'converter', 'snake_case', 'camelCase', 'kebab', 'uppercase', 'lowercase',
      'titre', 'majuscule', 'minuscule', 'convertir',
    ],
    acceptedMime: [],
    status: 'stable',
  },
  {
    id: 'count',
    category: 'text',
    href: '/text/count',
    i18nKey: 'tools.text.count',
    keywords: [
      'count', 'word', 'character', 'lines', 'paragraph', 'reading time',
      'compter', 'mots', 'caractères', 'lecture',
    ],
    acceptedMime: [],
    status: 'stable',
  },
  {
    id: 'lorem',
    category: 'text',
    href: '/text/lorem',
    i18nKey: 'tools.text.lorem',
    keywords: [
      'lorem', 'ipsum', 'placeholder', 'dummy text', 'generator',
      'texte', 'remplissage', 'fictif',
    ],
    acceptedMime: [],
    status: 'stable',
  },
  {
    id: 'diff',
    category: 'text',
    href: '/text/diff',
    i18nKey: 'tools.text.diff',
    keywords: [
      'diff', 'compare', 'text diff', 'comparison', 'differences', 'changes',
      'comparer', 'différences', 'difference', 'comparer textes',
    ],
    acceptedMime: [],
    status: 'stable',
  },
  {
    id: 'regex',
    category: 'text',
    href: '/text/regex',
    i18nKey: 'tools.text.regex',
    keywords: [
      'regex', 'regexp', 'regular expression', 'pattern', 'match', 'test', 'replace',
      'expression régulière', 'expressions régulières', 'tester', 'remplacer',
    ],
    acceptedMime: [],
    status: 'stable',
  },
  {
    id: 'slugify',
    category: 'text',
    href: '/text/slugify',
    i18nKey: 'tools.text.slugify',
    keywords: [
      'slug', 'slugify', 'url slug', 'kebab', 'permalink', 'seo slug',
      'générer slug', 'slug url', 'permalien',
    ],
    acceptedMime: [],
    status: 'stable',
  },
  {
    id: 'sort-lines',
    category: 'text',
    href: '/text/sort-lines',
    i18nKey: 'tools.text.sort-lines',
    keywords: [
      'sort lines', 'sort text', 'dedupe', 'alphabetical', 'numeric sort', 'shuffle',
      'trier lignes', 'trier texte', 'dédupliquer', 'alphabétique',
    ],
    acceptedMime: [],
    status: 'stable',
  },
  {
    id: 'escape',
    category: 'text',
    href: '/text/escape',
    i18nKey: 'tools.text.escape',
    keywords: [
      'escape', 'unescape', 'html escape', 'javascript escape', 'json escape', 'xml escape',
      'échapper', 'déséchapper', 'caractères spéciaux',
    ],
    acceptedMime: [],
    status: 'stable',
  },
  {
    id: 'whitespace',
    category: 'text',
    href: '/text/whitespace',
    i18nKey: 'tools.text.whitespace',
    keywords: [
      'whitespace', 'trim', 'normalize', 'tabs', 'spaces', 'line endings', 'crlf', 'lf',
      'espaces', 'normaliser', 'tabulations', 'sauts de ligne',
    ],
    acceptedMime: [],
    status: 'stable',
  },
  {
    id: 'markdown',
    category: 'text',
    href: '/text/markdown',
    i18nKey: 'tools.text.markdown',
    keywords: [
      'markdown', 'md', 'preview', 'render', 'html', 'commonmark', 'gfm',
      'aperçu', 'rendu', 'éditeur markdown',
    ],
    acceptedMime: [],
    status: 'stable',
  },
  {
    id: 'find-replace',
    category: 'text',
    href: '/text/find-replace',
    i18nKey: 'tools.text.find-replace',
    keywords: [
      'find', 'replace', 'find and replace', 'search replace', 'regex replace',
      'rechercher', 'remplacer', 'rechercher remplacer',
    ],
    acceptedMime: [],
    status: 'stable',
  },
  {
    id: 'focus',
    category: 'reading',
    href: '/reading/focus',
    i18nKey: 'tools.reading.focus',
    keywords: [
      'bionic reading', 'reading focus', 'guided reading', 'bold first letters', 'speed reading', 'dyslexia reading',
      'lecture rapide', 'lecture facilitée', 'dyslexie', 'lecture guidée',
    ],
    acceptedMime: [],
    status: 'stable',
  },
  {
    id: 'dyslexia-font',
    category: 'reading',
    href: '/reading/dyslexia-font',
    i18nKey: 'tools.reading.dyslexia-font',
    keywords: [
      'dyslexia font', 'text to dyslexia font', 'opendyslexic', 'dyslexia friendly', 'readable text', 'letter spacing', 'reading overlay',
      'police dyslexie', 'texte en police dyslexie', 'texte lisible', 'interligne', 'mise en forme dyslexie',
    ],
    acceptedMime: [],
    status: 'stable',
  },
  {
    id: 'pdf-dyslexia',
    category: 'reading',
    href: '/reading/pdf-dyslexia',
    i18nKey: 'tools.reading.pdf-dyslexia',
    keywords: [
      'dyslexia pdf', 'pdf to dyslexia font', 'make pdf readable', 'opendyslexic pdf', 'accessible pdf', 'reformat pdf',
      'pdf dyslexie', 'pdf en police dyslexie', 'pdf lisible', 'pdf accessible',
    ],
    acceptedMime: [],
    status: 'stable',
  },
  {
    id: 'read-aloud',
    category: 'reading',
    href: '/reading/read-aloud',
    i18nKey: 'tools.reading.read-aloud',
    keywords: [
      'text to speech', 'read aloud', 'tts', 'listen to text', 'dyslexia listen',
      'lecture à voix haute', 'synthèse vocale', 'lire le texte', 'voix',
    ],
    acceptedMime: [],
    status: 'stable',
  },
  {
    id: 'immersive',
    category: 'reading',
    href: '/reading/immersive',
    i18nKey: 'tools.reading.immersive',
    keywords: [
      'immersive reader', 'immersive reading', 'reading ruler', 'focus mode', 'line reader', 'dyslexia reader',
      'lecteur immersif', 'lecture immersive', 'règle de lecture', 'mode focus', 'lecture concentrée',
    ],
    acceptedMime: [],
    status: 'stable',
  },
  {
    id: 'base64',
    category: 'encode',
    href: '/encode/base64',
    i18nKey: 'tools.encode.base64',
    keywords: [
      'base64', 'encode', 'decode', 'data uri', 'file to base64',
      'encoder', 'décoder', 'fichier',
    ],
    acceptedMime: [],
    status: 'stable',
  },
  {
    id: 'url',
    category: 'encode',
    href: '/encode/url',
    i18nKey: 'tools.encode.url',
    keywords: [
      'url encode', 'url decode', 'percent encoding', 'encodeuricomponent',
      'urlencoded', 'encoder url', 'décoder url',
    ],
    acceptedMime: [],
    status: 'stable',
  },
  {
    id: 'jwt',
    category: 'encode',
    href: '/encode/jwt',
    i18nKey: 'tools.encode.jwt',
    keywords: [
      'jwt', 'json web token', 'decode jwt', 'inspect jwt', 'token decoder',
      'décoder jwt',
    ],
    acceptedMime: [],
    status: 'stable',
  },
  {
    id: 'hex',
    category: 'encode',
    href: '/encode/hex',
    i18nKey: 'tools.encode.hex',
    keywords: [
      'hex', 'hexadecimal', 'encode', 'decode', 'string to hex', 'hex to string',
      'encoder hex', 'décoder hex',
    ],
    acceptedMime: [],
    status: 'stable',
  },
  {
    id: 'html-entities',
    category: 'encode',
    href: '/encode/html-entities',
    i18nKey: 'tools.encode.html-entities',
    keywords: [
      'html entities', 'encode html', 'decode html', '&amp;', 'numeric character reference',
      'entités html', 'encoder html', 'décoder html',
    ],
    acceptedMime: [],
    status: 'stable',
  },
  {
    id: 'binary',
    category: 'encode',
    href: '/encode/binary',
    i18nKey: 'tools.encode.binary',
    keywords: [
      'binary', 'text to binary', 'binary to text', 'bits',
      'binaire', 'texte vers binaire', 'binaire vers texte',
    ],
    acceptedMime: [],
    status: 'stable',
  },
  {
    id: 'morse',
    category: 'encode',
    href: '/encode/morse',
    i18nKey: 'tools.encode.morse',
    keywords: [
      'morse', 'morse code', 'encode morse', 'decode morse', 'sos',
      'code morse', 'encoder morse', 'décoder morse',
    ],
    acceptedMime: [],
    status: 'stable',
  },
  {
    id: 'convert',
    category: 'color',
    href: '/color/convert',
    i18nKey: 'tools.color.convert',
    keywords: ['color', 'converter', 'hex', 'rgb', 'hsl', 'oklch', 'couleur', 'convertir'],
    acceptedMime: [],
    status: 'stable',
  },
  {
    id: 'contrast',
    category: 'color',
    href: '/color/contrast',
    i18nKey: 'tools.color.contrast',
    keywords: ['contrast', 'wcag', 'accessibility', 'a11y', 'ratio', 'aa', 'aaa', 'contraste', 'accessibilité'],
    acceptedMime: [],
    status: 'stable',
  },
  {
    id: 'palette',
    category: 'color',
    href: '/color/palette',
    i18nKey: 'tools.color.palette',
    keywords: ['palette', 'extract', 'image', 'colors', 'dominant', 'kmeans', 'extraire', 'couleurs'],
    acceptedMime: ['image/png', 'image/jpeg', 'image/webp'],
    status: 'stable',
  },
  {
    id: 'gradient',
    category: 'color',
    href: '/color/gradient',
    i18nKey: 'tools.color.gradient',
    keywords: [
      'gradient', 'css gradient', 'linear gradient', 'radial gradient', 'conic gradient',
      'dégradé', 'générateur dégradé', 'css',
    ],
    acceptedMime: [],
    status: 'stable',
  },
  {
    id: 'shades',
    category: 'color',
    href: '/color/shades',
    i18nKey: 'tools.color.shades',
    keywords: [
      'shades', 'tints', 'tones', 'palette generator', 'monochromatic',
      'nuances', 'teintes', 'monochrome',
    ],
    acceptedMime: [],
    status: 'stable',
  },
  {
    id: 'blender',
    category: 'color',
    href: '/color/blender',
    i18nKey: 'tools.color.blender',
    keywords: [
      'blend', 'mix', 'colors', 'interpolation', 'color scale',
      'mélanger', 'fondre', 'couleurs', 'dégradé',
    ],
    acceptedMime: [],
    status: 'stable',
  },
  {
    id: 'blindness',
    category: 'color',
    href: '/color/blindness',
    i18nKey: 'tools.color.blindness',
    keywords: [
      'color blindness', 'protanopia', 'deuteranopia', 'tritanopia', 'achromatopsia', 'simulator',
      'daltonisme', 'simulateur', 'accessibilité',
    ],
    acceptedMime: [],
    status: 'stable',
  },
  {
    id: 'generate',
    category: 'qr',
    href: '/qr/generate',
    i18nKey: 'tools.qr.generate',
    keywords: ['qr', 'qr code', 'generator', 'wifi qr', 'vcard qr', 'générer', 'générateur'],
    acceptedMime: [],
    status: 'stable',
  },
  {
    id: 'scan',
    category: 'qr',
    href: '/qr/scan',
    i18nKey: 'tools.qr.scan',
    keywords: ['qr', 'qr code', 'scanner', 'camera', 'scan', 'lecteur', 'lire'],
    acceptedMime: ['image/png', 'image/jpeg', 'image/webp'],
    status: 'stable',
  },
  {
    id: 'barcode-generate',
    category: 'qr',
    href: '/qr/barcode-generate',
    i18nKey: 'tools.qr.barcode-generate',
    keywords: [
      'barcode', 'code128', 'ean13', 'ean8', 'generator',
      'code-barres', 'générer', 'générateur',
    ],
    acceptedMime: [],
    status: 'stable',
  },
  {
    id: 'barcode-scan',
    category: 'qr',
    href: '/qr/barcode-scan',
    i18nKey: 'tools.qr.barcode-scan',
    keywords: [
      'barcode', 'scan', 'reader', 'decode', 'ean13', 'code128',
      'lecteur code-barres', 'scanner', 'décoder',
    ],
    acceptedMime: ['image/png', 'image/jpeg', 'image/webp'],
    status: 'stable',
  },
  {
    id: 'skills',
    category: 'dev',
    href: '/dev/skills',
    i18nKey: 'tools.dev.skills',
    keywords: [
      'skills', 'npx', 'install', 'claude code', 'cursor', 'codex',
      'gemini cli', 'copilot', 'agent skills', 'one-liner', 'cli',
      'installer', 'installateur', 'commande',
    ],
    acceptedMime: [],
    status: 'stable',
  },
  {
    id: 'skills-browse',
    category: 'dev',
    href: '/dev/skills-browse',
    i18nKey: 'tools.dev.skills-browse',
    keywords: [
      'skills', 'browse', 'search', 'skills.sh', 'discover',
      'install', 'claude code', 'cursor', 'codex', 'agent skills',
      'rechercher', 'explorer', 'parcourir', 'catalogue',
    ],
    acceptedMime: [],
    status: 'stable',
  },
] as const;

export function getTool(category: string, id: string): ToolMeta | undefined {
  return TOOLS.find((t) => t.category === category && t.id === id);
}

export function toolsByCategory(): Partial<Record<ToolCategory, ToolMeta[]>> {
  const acc: Partial<Record<ToolCategory, ToolMeta[]>> = {};
  for (const t of TOOLS) {
    (acc[t.category] ??= []).push(t);
  }
  return acc;
}

export function toolsForMime(mime: string): ToolMeta[] {
  return TOOLS.filter((t) => t.acceptedMime.includes(mime));
}
