// Curated 256-word English list for passphrase generation.
// 256 = 2^8 → exactly 8 bits of entropy per word.
// Hand-picked for: short (4-7 chars), common, easy to spell, no homophones.
export const PASSPHRASE_WORDLIST: readonly string[] = [
  'almond', 'anchor', 'angel', 'animal', 'apple', 'apricot', 'arrow', 'autumn',
  'avocado', 'baker', 'badger', 'balloon', 'bamboo', 'banana', 'basil', 'bench',
  'bird', 'blue', 'brain', 'bread', 'brick', 'brook', 'brush', 'bush',
  'candle', 'carbon', 'carrot', 'castle', 'cedar', 'chair', 'chalk', 'charm',
  'cheese', 'cherry', 'child', 'chip', 'cliff', 'cloth', 'cloud', 'clover',
  'coach', 'coast', 'coffee', 'coin', 'color', 'comet', 'compass', 'copper',
  'coral', 'cottage', 'country', 'courage', 'cousin', 'crater', 'creek', 'crystal',
  'daisy', 'dawn', 'dazzle', 'desert', 'diamond', 'dolphin', 'dragon', 'drift',
  'drum', 'dusk', 'eagle', 'earth', 'ember', 'energy', 'falcon', 'farm',
  'feather', 'festival', 'finger', 'flame', 'flower', 'forest', 'fossil', 'fountain',
  'fox', 'frost', 'garden', 'gemstone', 'ghost', 'ginger', 'glacier', 'gnome',
  'grain', 'granite', 'grape', 'grass', 'grove', 'harbor', 'harvest', 'hawk',
  'hazel', 'heart', 'hill', 'honey', 'horizon', 'ice', 'iguana', 'island',
  'ivy', 'jade', 'jasmine', 'jewel', 'jungle', 'juniper', 'kayak', 'kettle',
  'kite', 'kitten', 'koala', 'lagoon', 'lake', 'lantern', 'laurel', 'lavender',
  'leaf', 'lemon', 'light', 'lily', 'lion', 'lotus', 'marble', 'marigold',
  'meadow', 'melody', 'melon', 'meteor', 'mint', 'mirror', 'mist', 'monkey',
  'moon', 'moss', 'mountain', 'mushroom', 'music', 'nebula', 'nectar', 'nest',
  'ocean', 'olive', 'orange', 'orchard', 'orchid', 'otter', 'oven', 'owl',
  'palm', 'panda', 'parsley', 'peach', 'pearl', 'pebble', 'pelican', 'penguin',
  'petal', 'pine', 'plum', 'poppy', 'prairie', 'puppy', 'quartz', 'raccoon',
  'rain', 'rainbow', 'raven', 'ribbon', 'ridge', 'river', 'robin', 'rock',
  'rocket', 'rose', 'ruby', 'sage', 'salmon', 'sand', 'sapphire', 'saturn',
  'scarf', 'sea', 'seal', 'season', 'seed', 'shadow', 'shell', 'ship',
  'sky', 'snail', 'snake', 'snow', 'sparrow', 'sphere', 'spider', 'spring',
  'star', 'stone', 'stork', 'storm', 'stream', 'summer', 'sunflower', 'sunrise',
  'sunset', 'swan', 'sycamore', 'tangerine', 'tea', 'temple', 'thunder', 'tide',
  'tiger', 'tomato', 'topaz', 'torch', 'tower', 'tree', 'tulip', 'turkey',
  'turtle', 'twig', 'valley', 'vase', 'velvet', 'viola', 'violet', 'volcano',
  'walnut', 'watch', 'water', 'wave', 'whale', 'wheat', 'willow', 'wind',
  'window', 'wing', 'winter', 'wizard', 'wolf', 'wood', 'world', 'worm',
  'yellow', 'yogurt', 'zebra', 'zinnia', 'acorn', 'amber', 'antler', 'apron',
];
